from typing import List

def load_corpus() -> List[str]:
    corpus = [
        "y", "o", "pero", "sin embargo", "ademas", "luego", "entonces",
        "porque", "puesto que", "ya que", "aunque", "mientras", "durante",
        "despues", "antes", "finalmente", "inicialmente", "por lo tanto",
        "en conclusion", "es decir", "o sea", "es mas", "incluso", "tampoco",
        "ni siquiera", "a pesar de", "por contra", "al contrario", "en cambio",
        "ser", "estar", "tener", "hacer", "ir", "venir", "decir", "dar",
        "poder", "deber", "querer", "saber", "ver", "creer", "hablar", "llevar",
        "dejar", "seguir", "encontrar", "buscar", "llamar", "llegar", "partir",
        "entrar", "salir", "subir", "bajar", "sentir", "pensar", "conocer",
        "recordar", "olvidar", "esperar", "empezar", "terminar", "continuar",
        "comenzar", "parar", "cambiar", "aumentar", "disminuir", "mejorar",
        "empeorar", "ayudar", "servir", "trabajar", "estudiar", "aprender",
        "ensenar", "escuchar", "mirar", "escribir", "leer", "contar", "vivir",
        "morir", "nacer", "crecer", "beber", "comer", "dormir", "despertar",
        "cantar", "bailar", "jugar", "ganar", "perder", "comprar", "vender",
        "bueno", "malo", "grande", "pequeno", "nuevo", "viejo", "joven",
        "bonito", "feo", "hermoso", "horrible", "agradable", "desagradable",
        "rapido", "lento", "fuerte", "debil", "alto", "bajo", "largo", "corto",
        "ancho", "estrecho", "grueso", "delgado", "caliente", "frio", "tibio",
        "seco", "mojado", "limpio", "sucio", "claro", "oscuro", "brillante",
        "apagado", "suave", "duro", "blando", "aspero", "liso",
        "pesado", "ligero", "profundo", "superficial", "lleno", "vacio",
        "entero", "roto", "usado", "comun", "raro", "especial",
        "casa", "coche", "persona", "tiempo", "agua", "tierra", "fuego",
        "aire", "luz", "oscuridad", "color", "sonido", "musica", "palabra",
        "voz", "mirada", "mano", "pie", "cabeza", "corazon", "mente", "cuerpo",
        "vida", "muerte", "amor", "odio", "miedo", "alegria", "tristeza",
        "esperanza", "duda", "certeza", "verdad", "mentira", "mentiroso",
        "dinero", "precio", "costo", "valor", "riqueza", "pobreza", "trabajo",
        "descanso", "noche", "dia", "manana", "tarde", "hora",
        "minuto", "segundo", "semana", "mes", "ano", "siglo",
        "momento", "instante", "eternidad", "primavera", "verano", "otono",
        "invierno", "numero", "cifra", "cantidad", "calidad", "razon", "motivo",
        "causa", "efecto", "resultado", "conclusion", "comienzo", "fin", "mitad",
        "parte", "todo", "conjunto", "grupo", "multitud", "masa", "clase",
        "tipo", "especie", "forma", "figura", "objeto", "cosa", "asunto",
        "tema", "idea", "pensamiento", "sentimiento", "emocion", "pasion",
        "en", "de", "a", "por", "para", "con", "sin", "sobre", "bajo",
        "entre", "hacia", "desde", "hasta", "dentro", "fuera", "arriba",
        "abajo", "delante", "detras", "cerca", "lejos",
        "el", "la", "lo", "un", "una", "unos", "unas", "los", "las",
        "este", "ese", "aquel", "esta", "esa", "aquella", "esto", "eso",
        "aquello", "yo", "tu", "el", "ella", "nosotros", "vosotros",
        "ellos", "ellas", "mio", "tuyo", "suyo", "nuestro",
        "muy", "poco", "bastante", "demasiado", "apenas", "asi", "ahora",
        "aun", "hoy", "manana", "ayer", "siempre", "nunca", "jamas",
        "a veces", "algunas veces", "frecuentemente", "raramente", "aqui",
        "alla", "alla", "arriba", "abajo", "bien", "mal", "mejor", "peor", "facilmente",
        "dificilmente", "posiblemente", "probablemente", "ciertamente", "realmente",
        "verdaderamente", "completamente", "parcialmente", "mas", "menos",
        "tambien", "tampoco", "que", "cual", "cuando", "donde", "como",
        "cuanto", "cuantos", "cuan", "si", "cuando", "donde", "como",
        "quien", "quienes", "si", "no", "acaso", "quiza", "quizas", "tal",
        "amigo", "amiga", "enemigo", "enemiga", "hermano", "hermana", "padre",
        "madre", "hijo", "hija", "abuelo", "abuela", "nieto", "nieta",
        "tio", "tia", "primo", "prima", "esposo", "esposa", "marido", "pareja",
        "nombre", "apellido", "edad", "cumpleanos", "nacimiento",
        "boda", "divorcio", "matrimonio", "hombre", "mujer", "nino", "nina",
        "bebe", "adolescente", "adulto", "anciano", "anciana", "raza", "religion",
        "idioma", "lengua", "pais", "ciudad", "pueblo", "capital", "estado",
        "region", "provincia", "rio", "montana", "bosque", "selva", "desierto",
        "playa", "costa", "isla", "oceano", "mar", "lago", "laguna", "pozo",
        "puente", "camino", "calle", "avenida", "plaza", "parque", "jardin",
        "iglesia", "templo", "sinagoga", "mezquita", "monumento", "edificio",
        "castillo", "fortaleza", "muralla", "torre", "puerta", "ventana",
        "techo", "piso", "habitacion", "cocina", "bano", "salon", "dormitorio",
        "comedor", "biblioteca", "oficina", "fabrica", "tienda", "mercado",
        "restaurante", "bar", "cafe", "escuela", "universidad", "hospital",
        "medicina", "enfermedad", "salud", "doctor", "enfermera",
        "paciente", "sintoma", "remedio", "sanacion"
    ]
    return corpus